---
- name: Deploy Angular App to Web Server
  hosts: web-server1
  become: true

  vars:
    artifact_version: "{{ artifact_version }}"
    artifact_url: "s3://nottie-angular-app/artifacts/angular_app-{{ artifact_version }}.tar.gz"
    artifact_path: "/tmp/angular_app-{{ artifact_version }}.tar.gz"
    target_dir: "/var/www/html/angular_app"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download Angular App artifact from S3
      amazon.aws.s3_object:
        bucket: nottie-angular-app
        object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"
        dest: "{{ artifact_path }}"
        mode: get
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: us-east-1

    - name: Create target directory if it does not exist
      file:
        path: "{{ target_dir }}"
        state: directory
        mode: '0755'

    - name: Extract the Angular app artifact
      unarchive:
        src: "{{ artifact_path }}"
        dest: "{{ target_dir }}"
        remote_src: yes
        creates: "{{ target_dir }}/index.html"

    - name: Set permissions for the web server
      file:
        path: "{{ target_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Restart Apache to serve new content
      service:
        name: apache2
        state: restarted
