---
- name: Deploy Angular App to Web Server
  hosts: webserver
  become: true
  vars:
    s3_bucket: "nottie-angular-app"  # Pure bucket name without URI prefix
    artifact_version: "v27"  # Example version, should be passed as extra var
    target_dir: "/var/www/html/angular_app"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download Angular App artifact from S3
      amazon.aws.s3_object:  # Correct collection/module name
        bucket: "{{ s3_bucket }}"
        object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"  # Full object key
        dest: "/tmp/angular_app-{{ artifact_version }}.tar.gz"
        mode: get

    - name: Extract the Angular app artifact
      unarchive:
        src: "/tmp/angular_app-{{ artifact_version }}.tar.gz"
        dest: "{{ target_dir }}"
        remote_src: yes
        creates: "{{ target_dir }}/index.html"

    - name: Set permissions for the web server
      file:
        path: "{{ target_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Restart Apache to serve new content
      service:
        name: apache2
        state: restarted