---
- name: Deploy Angular App to Web Server
  hosts: web-server1
  become: true

  vars:
    artifact_version: "{{ artifact_version }}"
    artifact_url: "s3://nottie-angular-app/artifacts/angular_app-{{ artifact_version }}.tar.gz"
    artifact_path: "/tmp/angular_app-{{ artifact_version }}.tar.gz"
    deploy_base: "/var/www/html"
    versioned_dir: "{{ deploy_base }}/angular_app-{{ artifact_version }}"
    current_symlink: "{{ deploy_base }}/angular_app"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download Angular App artifact from S3
      amazon.aws.s3_object:
        bucket: nottie-angular-app
        object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"
        dest: "{{ artifact_path }}"
        mode: get
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: us-east-1

    - name: Create versioned deployment directory
      file:
        path: "{{ versioned_dir }}"
        state: directory
        mode: '0755'

    - name: Extract the Angular app artifact
      unarchive:
        src: "{{ artifact_path }}"
        dest: "{{ versioned_dir }}"
        remote_src: yes

    - name: Set permissions for the deployed files
      file:
        path: "{{ versioned_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Update the 'current' symlink to point to latest version
      file:
        src: "{{ versioned_dir }}"
        dest: "{{ current_symlink }}"
        state: link
        force: yes

    - name: Restart Apache to serve updated content
      service:
        name: apache2
        state: restarted

    - name: Clean up older versions, keep only the latest 3
      shell: |
        ls -dt {{ deploy_base }}/angular_app-* | grep -v angular_app$ | tail -n +4 | xargs rm -rf
      args:
        warn: false
