---
- name: Deploy Angular App
  hosts: all
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Download Angular App artifact from S3
      amazon.aws.s3:
        bucket: "nottie-angular-app"
        object: "artifacts/{{ artifact_version }}.tar.gz"
        dest: "/var/www/html/"
        mode: get
        profile: default  # Use the default profile
        region: "us-east-1"
      register: s3_download

    - name: Extract Angular App
      command:
        cmd: "tar -xzvf /var/www/html/angular_app-v27.tar.gz -C /var/www/html/"
      when: s3_download.changed

    - name: Restart Apache to serve the Angular app
      service:
        name: httpd
        state: restarted
      when: s3_download.changed
