- name: Download and deploy Angular app
  hosts: app_servers
  become: yes
  tasks:
    - name: Download artifact from S3
      get_url:
        url: "https://s3.amazonaws.com/your-s3-bucket-name/artifacts/{{ artifact_version }}/angular_app-{{ artifact_version }}.tar.gz"
        dest: "/tmp/angular_app.tar.gz"

    - name: Extract the artifact
      unarchive:
        src: "/tmp/angular_app.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

