---
- name: Deploy Angular App to Web Server
  hosts: web-server1
  become: true

  vars:
    artifact_version: "{{ artifact_version }}"
    artifact_url: "s3://nottie-angular-app/artifacts/angular_app-{{ artifact_version }}.tar.gz"
    artifact_path: "/tmp/angular_app-{{ artifact_version }}.tar.gz"
    target_dir: "/var/www/html/angular_app"
    versioned_dir: "/var/www/html/angular_app-{{ artifact_version }}"
    apache_config_file: "/etc/apache2/sites-available/000-default.conf"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download Angular App artifact from S3
      amazon.aws.s3_object:
        bucket: nottie-angular-app
        object: "artifacts/angular_app-{{ artifact_version }}.tar.gz"
        dest: "{{ artifact_path }}"
        mode: get
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: us-east-1

    - name: Create versioned target directory if it does not exist
      file:
        path: "{{ versioned_dir }}"
        state: directory
        mode: '0755'

    - name: Extract the Angular app artifact
      unarchive:
        src: "{{ artifact_path }}"
        dest: "{{ versioned_dir }}"
        remote_src: yes
        creates: "{{ versioned_dir }}/index.html"

    - name: Set permissions for the deployed files (versioned directory)
      file:
        path: "{{ versioned_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Remove existing 'current' symlink if it exists
      file:
        path: "{{ target_dir }}"
        state: absent
      when: target_dir is exists

    - name: Create or update 'current' symlink
      file:
        path: "{{ target_dir }}"
        src: "{{ versioned_dir }}"
        state: link

    - name: Update Apache config to point to the new DocumentRoot
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: '^DocumentRoot /var/www/html$'
        line: "DocumentRoot {{ target_dir }}"
        notify:
          - Restart Apache

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
      when: apache_config_file is changed

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
