- name: Configure MariaDB for remote access (optional)
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^#bind-address'
    line: "bind-address = 0.0.0.0"
  become: yes

- name: Restart MariaDB to apply changes
  service:
    name: mariadb
    state: restarted
  become: yes